name: Health check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    name: Check all sites
    permissions:
      contents: write
    env:
      TZ: Europe/Berlin
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: hustcer/setup-nu@v3
        with:
          version: "0.106.1"

      - run: nu ./health-check.nu urls.json

      - name: Configure Git and Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add logs/
          if ! git diff --staged --quiet; then
            git commit -m "[Automated] Update Health Check Logs"
            git push origin main
          else
            echo "No changes to commit"
          fi
